name: Push FitTrack Backend Image to Azure Registry

on:
  workflow_dispatch:

jobs:
  push-fittrack-backend:
    name: Build and Push FitTrack Backend Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: fittrack-backend
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.FITTRACK_AZURE_REGISTRY_PASSWORD }}" | docker login "${{ secrets.FITTRACK_AZURE_REGISTRY_SERVER }}" --username "${{ secrets.FITTRACK_AZURE_REGISTRY_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: |
          docker build -t "${{ secrets.FITTRACK_AZURE_REGISTRY_SERVER }}/$IMAGE_NAME:$IMAGE_TAG" ./backend

      - name: Push backend Docker image to Azure Container Registry
        run: |
          docker push "${{ secrets.FITTRACK_AZURE_REGISTRY_SERVER }}/$IMAGE_NAME:$IMAGE_TAG"
